#!/bin/bash
# lib/_prompts.sh
# Defines all user-facing prompt strings for the Secure Password Manager.

# Source color definitions to use in prompts
source "$(dirname "$0")/lib/_colors.sh"

# --- Master Password Change Prompts (from _change_master.sh) ---
PROMPT_CHANGE_MASTER_TITLE="${BRIGHT_BOLD}${VIOLET}--- Change Master Password ---${RESET}"
PROMPT_CHANGE_MASTER_HINT="${AQUA}You will be prompted to enter your current master password, then set a new one.${RESET}\n"
PROMPT_ENTER_CURRENT_MASTER_PASS="Enter current master password: "
ERROR_NO_PASSWORD_ENTERED="${NEON_RED}🚫 No password entered. Aborting.${RESET}"
ERROR_INCORRECT_CURRENT_MASTER_PASS="${NEON_RED}❌ Incorrect current master password. Aborting.${RESET}"
PROMPT_ENTER_NEW_MASTER_PASS="Enter NEW master password: "
ERROR_NEW_PASSWORD_NOT_SET="${NEON_RED}🚫 New password not set. Aborting.${RESET}"
WARNING_NEW_PASS_SAME_AS_CURRENT="${ELECTRIC_YELLOW}New password is the same as the current password. No changes made.${RESET}"
ERROR_ENCRYPT_NEW_PASS_FAILED="${NEON_RED}❌ Failed to encrypt data with new password. Aborting.${RESET}"
ERROR_MOVE_ENCRYPTED_FILE_FAILED="${NEON_RED}❌ Failed to move encrypted data to final file. Check permissions.${RESET}"
SUCCESS_MASTER_PASSWORD_CHANGED="${LIME_GREEN}✅ Master password successfully changed!${RESET}"

# --- General Utility Prompts (from _utils.sh) ---
PROMPT_CLEAR_SCREEN_TITLE_LINE1="${BRIGHT_BOLD}${VIOLET}=====================================================${RESET}"
PROMPT_CLEAR_SCREEN_TITLE_LINE2="${BRIGHT_BOLD}${AQUA}          ✨ Secure Password Manager ✨          ${RESET}"
PROMPT_CLEAR_SCREEN_TITLE_LINE3="${BRIGHT_BOLD}${VIOLET}=====================================================${RESET}\n"
PROMPT_PRESS_ENTER_TO_CONTINUE="\n${ELECTRIC_YELLOW}Press ${BRIGHT_BOLD}Enter${RESET}${ELECTRIC_YELLOW} to continue...${RESET}"
PROMPT_SPINNER_COMPLETE_MESSAGE="${LIME_GREEN}✓ %s Complete!         ${RESET}\n"
PROMPT_MASTER_PASSWORD_INPUT_GENERIC="${ELECTRIC_YELLOW}%s${RESET}" # Placeholder for dynamic prompt
ERROR_MASTER_PASSWORD_EMPTY="${NEON_RED}🚫 Master password cannot be empty! Please try again.${RESET}"
PROMPT_CONFIRM_MASTER_PASSWORD="${ELECTRIC_YELLOW}Confirm your master password: ${RESET}"
ERROR_PASSWORDS_DO_NOT_MATCH="${NEON_RED}🚫 Passwords do not match. Please try again.${RESET}"
PROMPT_OPTIONAL_INPUT_WITH_REMOVE="${ELECTRIC_YELLOW}%s (current: ${BRIGHT_BOLD}%s${RESET}) [${LIME_GREEN}Leave BLANK: Keep${RESET} | ${NEON_RED}Type 'X': Remove${RESET}]:${RESET} "
PROMPT_FIELD_WILL_BE_REMOVED="${AQUA}Field will be removed.${RESET}"
PROMPT_MANDATORY_INPUT_CONDITIONAL="${ELECTRIC_YELLOW}%s (current: ${BRIGHT_BOLD}%s${RESET}, cannot be empty):${RESET} "
ERROR_FIELD_CANNOT_BE_EMPTY="${NEON_RED}🚫 This field cannot be empty! Please provide a value or type '${AQUA}C${NEON_RED}' to cancel.${RESET}"
WARNING_NO_CLIPBOARD_UTILITY="${ELECTRIC_YELLOW}⚠️  No clipboard utility found. Please install xclip or pbcopy.${RESET}"

# --- CRUD Operations Prompts (from _crud_operations.sh) ---
# Add Entry
PROMPT_ADD_ENTRY_TITLE="${BRIGHT_BOLD}${VIOLET}--- Add New Credential Entry ---${RESET}"
PROMPT_CANCEL_OPERATION_HINT="${AQUA}💡 At any point, type '${BRIGHT_BOLD}C${RESET}${AQUA}' to cancel this operation.${RESET}\n"
PROMPT_ENTER_WEBSITE_NAME="🌐 Enter Website Name: "
ERROR_WEBSITE_EMPTY="${NEON_RED}🚫 Website/Service name cannot be empty! Please provide a value or type ${AQUA}'C'${RESET}${NEON_RED} to cancel.${RESET}"
PROMPT_LOGGED_IN_VIA_DEFAULT="🔗 Did you log into this site using another service (e.g., Google, Facebook)? (Default: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, Leave blank if not, '${BRIGHT_BOLD}X${RESET}${ELECTRIC_YELLOW}' to clear default): "
PROMPT_LOGGED_IN_VIA="🔗 Did you log into this site using another service (e.g., Google, Facebook)? (Leave blank if not): "
PROMPT_DEFAULT_SERVICE_CLEARED="${AQUA}Default service cleared for this entry.${RESET}"
PROMPT_USING_DEFAULT_SERVICE="${AQUA}Using default service: ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_OPERATION_CANCELLED_RETURN_MENU="${AQUA}Operation cancelled. Returning to main menu.${RESET}"
PROMPT_LINKED_EMAIL_DEFAULT="📧 Enter the email used for ${BRIGHT_BOLD}%s${RESET} ${ELECTRIC_YELLOW}(Default: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, cannot be empty, '${BRIGHT_BOLD}X${RESET}'${ELECTRIC_YELLOW} to clear default, type '${BRIGHT_BOLD}C${RESET}'${ELECTRIC_YELLOW} to cancel): "
PROMPT_LINKED_EMAIL="📧 Enter the email used for ${BRIGHT_BOLD}%s${RESET} ${ELECTRIC_YELLOW}(cannot be empty, type '${BRIGHT_BOLD}C${RESET}'${ELECTRIC_YELLOW} to cancel): "
PROMPT_DEFAULT_EMAIL_CLEARED="${AQUA}Default email cleared for this entry.${RESET}"
PROMPT_USING_DEFAULT_EMAIL="${AQUA}Using default email: ${BRIGHT_BOLD}%s${RESET}.${RESET}"
ERROR_LINKED_EMAIL_EMPTY="${NEON_RED}🚫 Linked email cannot be empty if a service is specified! Please provide a value or type '${AQUA}C${RESET}'${NEON_RED} to cancel.${RESET}"
PROMPT_ENTER_USERNAME_OPTIONAL="👤 Enter a username for this service (optional, leave blank if none): "
PROMPT_EMAIL_DEFAULT="📧 Enter your Email for this site (Default: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, cannot be empty, or type 'U' to use username, '${BRIGHT_BOLD}X${RESET}${ELECTRIC_YELLOW}' to clear default): "
PROMPT_EMAIL="📧 Enter your Email for this site (cannot be empty, or type 'U' to use username): "
PROMPT_ENTER_USERNAME_MANDATORY="👤 Enter your Username for this site (cannot be empty): "
ERROR_USERNAME_EMPTY="${NEON_RED}🚫 Username cannot be empty! Please provide a value or type '${AQUA}C' to cancel.${RESET}"
ERROR_EMAIL_EMPTY_OR_USERNAME_OPTION="${NEON_RED}🚫 Email cannot be empty! Please provide a value, type '${AQUA}C' to cancel, or '${AQUA}U' to use username.${RESET}"
PROMPT_ENTER_USERNAME_OPTIONAL_EMAIL_USED="👤 Enter a username for this site (optional, leave blank if none): "
PROMPT_RECOVERY_EMAIL_OPTIONAL="🚨 Recovery Email (optional, leave blank if none): "
PROMPT_GENERATE_PASSWORD="🔑 Generate a random password for this entry? (${BRIGHT_BOLD}y/N${RESET}${ELECTRIC_YELLOW}):"
ERROR_INVALID_YES_NO_INPUT="${NEON_RED}🚫 Invalid input. Please enter '${BRIGHT_BOLD}Y${RESET}${NEON_RED}' for Yes, '${BRIGHT_BOLD}N${RESET}${NEON_RED}' for No, or '${AQUA}C${NEON_RED}' to cancel.${RESET}"
PROMPT_GENERATED_PASSWORD="${LIME_GREEN}🔐 Generated password using default settings: ${BRIGHT_BOLD}%s${RESET}\n"
PROMPT_ENTER_SERVICE_PASSWORD_OPTIONAL="🔑 Enter service password (optional, leave blank if none): "
PROMPT_ENTER_WEBSITE_PASSWORD_MANDATORY="🔑 Enter website password (cannot be empty): "
ERROR_WEBSITE_PASSWORD_EMPTY="${NEON_RED}🚫 Website password cannot be empty! Please provide a value or type '${AQUA}C' to cancel.${RESET}"
PROMPT_REVIEW_NEW_ENTRY="${BRIGHT_BOLD}${CYBER_BLUE}--- Review New Entry ---${RESET}"
PROMPT_CONFIRM_SAVE_ENTRY="Do you want to ${BRIGHT_BOLD}SAVE${RESET}${ELECTRIC_YELLOW} this entry? (${BRIGHT_BOLD}Y/n${RESET}${ELECTRIC_YELLOW}):"
PROMPT_ENTRY_NOT_SAVED="${AQUA}Entry not saved. Returning to main menu.${RESET}"
SUCCESS_ENTRY_ADDED_SAVED="${LIME_GREEN}✅ Entry successfully added and saved!${RESET}"

# Edit Entry
PROMPT_EDIT_ENTRY_TITLE="${BRIGHT_BOLD}${VIOLET}--- Edit Existing Credential Entry ---${RESET}"
PROMPT_NO_ENTRIES_TO_EDIT="${ELECTRIC_YELLOW}No entries to edit. Please add some first.${RESET}"
PROMPT_CHOOSE_ENTRY_TO_EDIT="${AQUA}Choose an entry to edit by its number:${RESET}"
PROMPT_ENTER_ENTRY_NUMBER_TO_EDIT="Enter the number of the entry to edit [1-%d]:"
ERROR_INVALID_ENTRY_NUMBER="${NEON_RED}🚫 Invalid input. Please enter a number between 1 and %d, or type '${AQUA}C${NEON_RED}' to cancel.${RESET}"
PROMPT_CURRENTLY_SELECTED_ENTRY="${BRIGHT_BOLD}${CYBER_BLUE}--- Currently Selected Entry (#%d) ---${RESET}"
PROMPT_EDITING_HINT="${AQUA}You are now editing this entry. Use the options provided for each field.${RESET}"
PROMPT_UPDATE_WEBSITE_NAME="🌐 Update Website/Service Name (current: ${BRIGHT_BOLD}%s${RESET}):"
PROMPT_KEEPING_CURRENT_WEBSITE="${AQUA}Keeping current website: ${BRIGHT_BOLD}%s${RESET}${RESET}\n"
PROMPT_UPDATE_LOGGED_IN_VIA="🔗 Update Logged in via"
PROMPT_UPDATE_LINKED_EMAIL="📧 Update Linked email for %s"
PROMPT_UPDATE_USERNAME_FOR_SERVICE="👤 Update Username for %s"
WARNING_BOTH_EMAIL_USERNAME_EMPTY_SERVICE_REMOVED="${ELECTRIC_YELLOW}Both Linked email and Username were removed or left blank, therefore 'Logged in via' will also be removed for consistency.${RESET}"
PROMPT_UPDATE_EMAIL="📧 Update Email"
PROMPT_UPDATE_USERNAME="👤 Update Username"
ERROR_EMAIL_OR_USERNAME_REQUIRED="${NEON_RED}🚫 Either Email or Username is required! Please provide at least one.${RESET}"
PROMPT_UPDATE_RECOVERY_EMAIL="🚨 Update Recovery Email"
PROMPT_GENERATE_NEW_PASSWORD="🔑 Generate a new random password for this entry? (${BRIGHT_BOLD}y/N${RESET}${ELECTRIC_YELLOW}):"
PROMPT_NEW_PASSWORD_LENGTH="🔢 New password length (default: ${BRIGHT_BOLD}%s${RESET}):"
ERROR_INVALID_LENGTH="${NEON_RED}🚫 Invalid length. Please enter a positive number or type '${AQUA}C${NEON_RED}' to cancel.${RESET}"
PROMPT_INCLUDE_UPPERCASE="⬆️ Include uppercase letters? (default: ${BRIGHT_BOLD}%s${RESET}):"
PROMPT_INCLUDE_NUMBERS="🔢 Include numbers? (default: ${BRIGHT_BOLD}%s${RESET}):"
PROMPT_INCLUDE_SYMBOLS="🔣 Include symbols? (default: ${BRIGHT_BOLD}%s${RESET}):"
PROMPT_GENERATED_NEW_PASSWORD="${LIME_GREEN}🔐 Generated new password: ${BRIGHT_BOLD}%s${RESET}\n"
PROMPT_UPDATE_WEBSITE_PASSWORD="🔑 Update Website password"
PROMPT_REVIEW_UPDATED_ENTRY="${BRIGHT_BOLD}${CYBER_BLUE}--- Review Updated Entry ---${RESET}"
PROMPT_CONFIRM_SAVE_CHANGES="Do you want to ${BRIGHT_BOLD}SAVE${RESET}${ELECTRIC_YELLOW} these changes? (${BRIGHT_BOLD}Y/n${RESET}${ELECTRIC_YELLOW}):"
PROMPT_CHANGES_NOT_SAVED="${AQUA}Changes not saved. Returning to main menu.${RESET}"
SUCCESS_ENTRY_UPDATED_SAVED="${LIME_GREEN}✅ Entry successfully updated and saved!${RESET}"

# Remove Entry
PROMPT_REMOVE_ENTRY_TITLE="${BRIGHT_BOLD}${VIOLET}--- Remove Credential Entries ---${RESET}"
PROMPT_NO_ENTRIES_TO_REMOVE="${ELECTRIC_YELLOW}No entries to remove. Please add some first.${RESET}"
PROMPT_CHOOSE_ENTRY_TO_REMOVE="${AQUA}Choose an entry to edit by its number:${RESET}"
PROMPT_ENTER_NUMBERS_TO_REMOVE="Enter numbers of entries to remove (e.g., '${BRIGHT_BOLD}1,3,5${RESET}${ELECTRIC_YELLOW}'):"
ERROR_INVALID_ENTRY_NUMBER_REMOVE="${NEON_RED}🚫 Invalid entry number: '%s'. Please enter valid numbers or type '${AQUA}C${NEON_RED}' to cancel.${RESET}"
ERROR_NO_VALID_ENTRIES_SELECTED="${NEON_RED}🚫 No valid entries selected. Please enter at least one number, or type '${AQUA}C${NEON_RED}' to cancel.${RESET}"
PROMPT_ENTRIES_TO_BE_PERMANENTLY_REMOVED="${BRIGHT_BOLD}${CYBER_BLUE}--- Entries to be Permanently Removed ---${RESET}"
PROMPT_REMOVING_ENTRY="${AQUA}Removing entry %d...${RESET}"
PROMPT_CONFIRM_PERMANENT_REMOVAL="Are you ${BRIGHT_BOLD}SURE${RESET}${ELECTRIC_YELLOW} you want to PERMANENTLY remove these entries? (${NEON_RED}y/N${RESET}${ELECTRIC_YELLOW}):"
ERROR_INVALID_YES_NO_INPUT_REMOVE="${NEON_RED}🚫 Invalid input. Please enter '${BRIGHT_BOLD}Y${RESET}${NEON_RED}' for Yes, '${BRIGHT_BOLD}N${NEON_RED}' for No, or '${AQUA}C${NEON_RED}' to cancel.${RESET}"
PROMPT_REMOVAL_CANCELLED="${AQUA}Removal cancelled. Returning to main menu.${RESET}"
SUCCESS_ENTRIES_REMOVED="${LIME_GREEN}✅ Selected entries removed successfully!${RESET}"
PROMPT_REMOVAL_CANCELLED_GENERIC="${AQUA}Removal cancelled.${RESET}"

# --- Display and Search Prompts (from _display_search.sh) ---
PROMPT_SEARCH_CREDENTIALS_TITLE="${BRIGHT_BOLD}${VIOLET}--- Search Credentials ---${RESET}"
PROMPT_SEARCH_FIELDS_HINT="🔎 Select which fields to filter by. You can pick multiple, separated by commas (e.g. 1,3,5).${RESET}\n"
PROMPT_SEARCH_ENTER_FIELD_NUMBERS="Enter field numbers to filter by (comma-separated), or press Enter to show all:"
PROMPT_SEARCH_WEBSITE_CONTAINS="🌐 Website contains"
PROMPT_SEARCH_EMAIL_CONTAINS="📧 Email contains"
PROMPT_SEARCH_USERNAME_CONTAINS="👤 Username contains"
PROMPT_SEARCH_LOGGED_IN_VIA_CONTAINS="🔗 Logged in via contains"
PROMPT_SEARCH_LINKED_EMAIL_CONTAINS="📧 Linked email contains"
PROMPT_SEARCH_RECOVERY_EMAIL_CONTAINS="🚨 Recovery email contains"
PROMPT_SEARCHING_MESSAGE="${AQUA}Searching for matching credentials...${RESET}\n"
ERROR_NO_MATCHING_ENTRIES="${NEON_RED}❌ No matching entries found based on your filters.${RESET}"
PROMPT_MATCHING_ENTRIES_FOUND="${LIME_GREEN}--- Matching Entries Found ---${RESET}"
PROMPT_HOW_TO_COMBINE_FILTERS="${ELECTRIC_YELLOW}How should filters be combined? (Current default: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW})${RESET}"
PROMPT_MATCH_ALL_FILTERS="${BRIGHT_BOLD}1)${RESET} Match ${BRIGHT_BOLD}ALL${RESET} filters (AND)"
PROMPT_MATCH_ANY_FILTER="${BRIGHT_BOLD}2)${RESET} Match ${BRIGHT_BOLD}ANY${RESET} filter (OR)"
PROMPT_ENTER_FILTER_MODE="Enter 1 for AND, 2 for OR [default: Use configured default]:"
PROMPT_COPY_FIELD_QUESTION="${ELECTRIC_YELLOW}Would you like to copy a field from a result to the clipboard?${RESET}"
PROMPT_ENTER_RESULT_NUMBER_TO_COPY="Enter result number [1-%d] to copy, or press Enter to skip:"
PROMPT_NO_FIELDS_TO_COPY="${ELECTRIC_YELLOW}No available fields to copy for this entry.${RESET}"
PROMPT_WHICH_FIELD_TO_COPY="${ELECTRIC_YELLOW}Which field do you want to copy?${RESET}"
PROMPT_ENTER_FIELD_NUMBER_TO_COPY="Enter field number [1-%d]:"
SUCCESS_COPIED_TO_CLIPBOARD="${LIME_GREEN}Copied to clipboard!${RESET}"
WARNING_NO_VALUE_FOR_FIELD="${ELECTRIC_YELLOW}No value found for the selected field.${RESET}"

# View All Entries
PROMPT_VIEW_ALL_CREDENTIALS_TITLE="${BRIGHT_BOLD}${VIOLET}--- View All Credentials ---${RESET}\n"
PROMPT_NO_ENTRIES_FOUND_YET="${ELECTRIC_YELLOW}No entries found yet. Start by adding a new one!${RESET}"
PROMPT_ALL_SAVED_CREDENTIALS="${BRIGHT_BOLD}All saved credentials (%d entries):${RESET}"
PROMPT_COPY_FIELD_FROM_ALL_ENTRIES_QUESTION="${ELECTRIC_YELLOW}Would you like to copy a field from an entry to the clipboard?${RESET}"
PROMPT_ENTER_ENTRY_NUMBER_TO_COPY="Enter entry number [1-%d] to copy, or press Enter to skip:"

# --- Configuration Prompts (from _config.sh) ---
PROMPT_MANAGE_SETTINGS_TITLE="${BRIGHT_BOLD}${VIOLET}--- Manage Settings ---${RESET}"
PROMPT_MANAGE_SETTINGS_HINT="${AQUA}Configure default password generation and data file location.${RESET}\n"
PROMPT_CURRENT_SETTINGS="${BRIGHT_BOLD}Current Settings:${RESET}"
PROMPT_SETTING_PASSWORD_LENGTH="  ${BRIGHT_BOLD}1)${RESET} Default Password Length: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_INCLUDE_UPPERCASE="  ${BRIGHT_BOLD}2)${RESET} Include Uppercase: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_INCLUDE_NUMBERS="  ${BRIGHT_BOLD}3)${RESET} Include Numbers: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_INCLUDE_SYMBOLS="  ${BRIGHT_BOLD}4)${RESET} Include Symbols: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_CLIPBOARD_DELAY="  ${BRIGHT_BOLD}5)${RESET} Clipboard Clear Delay (seconds): ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_DATA_FILE_LOCATION="  ${BRIGHT_BOLD}6)${RESET} Default Data File Location: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_SEARCH_MODE="  ${BRIGHT_BOLD}7)${RESET} Default Search Mode: ${BRIGHT_BOLD}%s${RESET} ('and' or 'or')"
PROMPT_SETTING_DEFAULT_EMAIL="  ${BRIGHT_BOLD}8)${RESET} Default Email: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_DEFAULT_SERVICE="  ${BRIGHT_BOLD}9)${RESET} Default Service: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_BACK_TO_MAIN_MENU="  ${BRIGHT_BOLD}Q)${RESET} Back to Main Menu${RESET}\n"
PROMPT_ENTER_SETTING_CHOICE="Enter setting number to change, or 'Q' to quit: "
ERROR_INVALID_OPTION_SETTINGS="${NEON_RED}❌ Invalid option. Please enter a number from 1-9 or 'Q'.${RESET}"
PROMPT_ENTER_NEW_PASSWORD_LENGTH="Enter new default password length (current: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, min 1):"
ERROR_INVALID_LENGTH_POSITIVE_NUMBER="${NEON_RED}🚫 Invalid length. Please enter a positive number.${RESET}"
SUCCESS_PASSWORD_LENGTH_UPDATED="${LIME_GREEN}Default password length updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_INCLUDE_UPPERCASE_QUESTION="Include uppercase letters? (current: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, Y/n): "
SUCCESS_INCLUDE_UPPERCASE_UPDATED="${LIME_GREEN}Include uppercase updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_INCLUDE_NUMBERS_QUESTION="Include numbers? (current: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, Y/n): "
SUCCESS_INCLUDE_NUMBERS_UPDATED="${LIME_GREEN}Include numbers updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_INCLUDE_SYMBOLS_QUESTION="Include symbols? (current: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, Y/n): "
SUCCESS_INCLUDE_SYMBOLS_UPDATED="${LIME_GREEN}Include symbols updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_ENTER_NEW_CLIPBOARD_DELAY="Enter new clipboard clear delay in seconds (current: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, 0 for no clear):"
ERROR_INVALID_DELAY_NON_NEGATIVE="${NEON_RED}🚫 Invalid delay. Please enter a non-negative number.${RESET}"
SUCCESS_CLIPBOARD_DELAY_UPDATED="${LIME_GREEN}Clipboard clear delay updated to ${BRIGHT_BOLD}%s${RESET} seconds.${RESET}"
PROMPT_ENTER_NEW_SAVE_LOCATION="Enter new default data file directory (current: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}):"
ERROR_DIRECTORY_NOT_FOUND="${NEON_RED}🚫 Directory not found. Please enter a valid directory path.${RESET}"
SUCCESS_DATA_FILE_LOCATION_UPDATED="${LIME_GREEN}Default data file location updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
INFO_ENCRYPTED_FILE_LOCATION="${ELECTRIC_YELLOW}Encrypted file will now be saved/loaded from: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}.${RESET}"
PROMPT_ENTER_NEW_SEARCH_MODE="Enter new default search mode (current: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, 'and' or 'or'): "
ERROR_INVALID_SEARCH_MODE="${NEON_RED}🚫 Invalid input. Please enter 'and' or 'or'.${RESET}"
SUCCESS_SEARCH_MODE_UPDATED="${LIME_GREEN}Default search mode updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_ENTER_NEW_DEFAULT_EMAIL="Enter new default email (current: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, leave blank to clear, or type '${BRIGHT_BOLD}C${RESET}${ELECTRIC_YELLOW}' to cancel): "
INFO_DEFAULT_EMAIL_CANCELLED="${AQUA}Default email configuration cancelled.${RESET}"
SUCCESS_DEFAULT_EMAIL_UPDATED="${LIME_GREEN}Default email updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_ENTER_NEW_DEFAULT_SERVICE="Enter new default service (current: ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}, leave blank to clear, or type '${BRIGHT_BOLD}C${RESET}${ELECTRIC_YELLOW}' to cancel): "
INFO_DEFAULT_SERVICE_CANCELLED="${AQUA}Default service configuration cancelled.${RESET}"
SUCCESS_DEFAULT_SERVICE_UPDATED="${LIME_GREEN}Default service updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
INFO_CONFIG_LOADING="${AQUA}Loading configuration from ${BRIGHT_BOLD}%s${RESET}${AQUA}...${RESET}"
SUCCESS_CONFIG_LOADED="${LIME_GREEN}Configuration loaded.${RESET}\n"
WARNING_NO_CONFIG_FILE="${ELECTRIC_YELLOW}No configuration file found. Using default settings.${RESET}\n"
SUCCESS_CONFIG_SAVED="${LIME_GREEN}Configuration saved to ${BRIGHT_BOLD}%s${RESET}${LIME_GREEN}.${RESET}"
SUCCESS_DEFAULT_SAVE_LOCATION_UPDATED="${LIME_GREEN}Default save location updated to: ${BRIGHT_BOLD}%s${RESET}${LIME_GREEN}.${RESET}"

# --- Crypto Prompts (from _crypto.sh) ---
INFO_SKIPPING_SAVE_NOT_AUTH="\n${BRIGHT_BOLD}${CYBER_BLUE}-----------------------------------------------------${RESET}\n  🔐 Skipping save: Not authenticated or master password not set.${RESET}\n${BRIGHT_BOLD}${CYBER_BLUE}-----------------------------------------------------${RESET}"
IMPORTANT_SECURITY_REMINDER_HEADER="\n${BRIGHT_BOLD}${NEON_RED}--- IMPORTANT SECURITY REMINDER ---${RESET}"
IMPORTANT_SECURITY_REMINDER_LINE1="${NEON_RED}Your password data was handled in-memory during this session.${RESET}"
IMPORTANT_SECURITY_REMINDER_LINE2="${NEON_RED}No plaintext data should have been written to disk.${RESET}"
IMPORTANT_SECURITY_REMINDER_LINE3="${NEON_RED}For maximum security, always ensure your system is free from malware and memory dumps are cleared.${RESET}"
IMPORTANT_SECURITY_REMINDER_FOOTER="${BRIGHT_BOLD}${NEON_RED}-----------------------------------${RESET}"
SUCCESS_CREDENTIALS_SAVED="${LIME_GREEN}✅ Credentials securely saved to ${BRIGHT_BOLD}%s${RESET}${LIME_GREEN}.${RESET}"
ERROR_FAILED_TO_MOVE_ENCRYPTED_DATA="${NEON_RED}❌ Failed to move encrypted data to final file. Check permissions.${RESET}"

# --- External File Load Prompts (from _data_storage.sh) ---
PROMPT_LOAD_EXTERNAL_TITLE="${BRIGHT_BOLD}${VIOLET}--- Load External Credentials File ---${RESET}"
PROMPT_LOAD_EXTERNAL_HINT="${AQUA}💡 Enter the full path to the encrypted file you wish to load.${RESET}"
PROMPT_LOAD_EXTERNAL_CANCEL_HINT="${AQUA}Type '${BRIGHT_BOLD}C${RESET}${AQUA}' to cancel.${RESET}\n"
PROMPT_ENTER_EXTERNAL_FILE_PATH="${ELECTRIC_YELLOW}📁 Enter path to encrypted file: ${RESET}"
ERROR_FILE_NOT_FOUND="${NEON_RED}❌ File not found at '${BRIGHT_BOLD}%s${RESET}${NEON_RED}'. Please enter a valid path or type '${AQUA}C${NEON_RED}' to cancel.${RESET}"
PROMPT_ENTER_EXTERNAL_FILE_MASTER_PASS="🔑 Enter master password for '${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}': ${RESET}"
ERROR_EXTERNAL_MASTER_PASSWORD_NOT_PROVIDED="${NEON_RED}🚫 Master password not provided. Aborting load.${RESET}"
INFO_ATTEMPTING_DECRYPT_EXTERNAL="${AQUA}Attempting to decrypt and load credentials from ${BRIGHT_BOLD}%s${RESET}${AQUA}...${RESET}"
SUCCESS_EXTERNAL_FILE_LOADED="${LIME_GREEN}✅ Credentials from ${BRIGHT_BOLD}%s${RESET}${LIME_GREEN} loaded successfully!${RESET}"
PROMPT_MAKE_EXTERNAL_FILE_DEFAULT="${ELECTRIC_YELLOW}Do you want to make this the ${BRIGHT_BOLD}default${RESET}${ELECTRIC_YELLOW} credentials file for future sessions? (${BRIGHT_BOLD}y/N${RESET}${ELECTRIC_YELLOW}):${RESET}"
INFO_EXTERNAL_FILE_LOADED_TEMPORARILY="${AQUA}File loaded temporarily.${RESET}"
ERROR_INVALID_YES_NO_INPUT_EXTERNAL="${NEON_RED}🚫 Invalid input. Please enter '${BRIGHT_BOLD}Y${RESET}${NEON_RED}' for Yes, '${BRIGHT_BOLD}N${RESET}${NEON_RED}' for No, or '${AQUA}C${NEON_RED}' to cancel.${RESET}"
SUCCESS_EXTERNAL_FILE_SET_DEFAULT="${LIME_GREEN}This file is now set as your default credentials file.${RESET}"
ERROR_FAILED_LOAD_EXTERNAL_CREDENTIALS="${NEON_RED}❌ Failed to load external credentials. Please check the password and file integrity.${RESET}"

# --- Main Application (passman.sh) Prompts ---
INFO_DEPENDENCY_CHECKING="${AQUA}Checking system dependencies...${RESET}"
ERROR_JQ_NOT_INSTALLED="${NEON_RED}${BRIGHT_BOLD}Error: 'jq' is not installed.${RESET}\n${NEON_RED}Please install 'jq' to use this script (e.g., on Debian/Ubuntu: ${ELECTRIC_YELLOW}sudo apt-get install jq${NEON_RED}).${RESET}"
ERROR_OPENSSL_NOT_INSTALLED="${NEON_RED}${BRIGHT_BOLD}Error: 'openssl' is not installed.${RESET}\n${NEON_RED}Please install 'openssl' to use this script (e.g., on Debian/Ubuntu: ${ELECTRIC_YELLOW}sudo apt-get install openssl${NEON_RED}).${RESET}"
WARNING_CLIPBOARD_NOT_AVAILABLE="${ELECTRIC_YELLOW}⚠️  Clipboard integration not available. Install ${BRIGHT_BOLD}xclip${RESET}${ELECTRIC_YELLOW} (Linux) or ${BRIGHT_BOLD}pbcopy${RESET}${ELECTRIC_YELLOW} (macOS) for copy-to-clipboard support.${RESET}"
SUCCESS_DEPENDENCIES_MET="${LIME_GREEN}Dependencies met. Proceeding...${RESET}\n"
WARNING_NO_ENC_FILE_FOUND="${ELECTRIC_YELLOW}🔑 No encrypted credentials file found at ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}. This appears to be your first run or the file was moved.${RESET}"
INFO_SET_MASTER_PASSWORD_PROMPT="${ELECTRIC_YELLOW}You'll be prompted to set up your master password for encryption.${RESET}"
WARNING_NO_RECOVERY="${BRIGHT_BOLD}${NEON_RED}🚨 WARNING: Remember this password! There is NO recovery if you forget it.${RESET}"
PROMPT_SET_NEW_MASTER_PASSWORD="Set your new master password: "
ERROR_MASTER_PASSWORD_NOT_SET_EXIT="${NEON_RED}🚫 Master password not set. Exiting.${RESET}"
SUCCESS_INITIAL_FILE_CREATED="${LIME_GREEN}✅ Initial credentials file created and encrypted!${RESET}"
PROMPT_WELCOME_BACK_TITLE="${BRIGHT_BOLD}${VIOLET}--- Welcome Back! ---${RESET}"
PROMPT_UNLOCK_CREDENTIALS_HINT="${AQUA}Enter your master password to unlock your credentials.${RESET}\n"
PROMPT_ENTER_MASTER_PASSWORD_TO_UNLOCK="🔑 Enter master password to unlock: "
ERROR_MASTER_PASSWORD_NOT_PROVIDED_EXIT="${NEON_RED}🚫 Master password not provided. Exiting.${RESET}"
INFO_DECRYPTING_CREDENTIALS="${AQUA}Attempting to decrypt credentials from ${BRIGHT_BOLD}%s${RESET}${AQUA}...${RESET}"
SUCCESS_CREDENTIALS_DECRYPTED="${LIME_GREEN}✅ Credentials decrypted successfully!${RESET}"
ERROR_INCORRECT_MASTER_PASSWORD_OR_CORRUPTED="${NEON_RED}❌ Incorrect master password or corrupted file. Please verify your password and try again.${RESET}"
PROMPT_MAIN_MENU_TITLE="${BRIGHT_BOLD}${VIOLET}--- Main Menu ---${RESET}"
PROMPT_MAIN_MENU_HINT="${AQUA}Select an option to manage your passwords.${RESET}\n"
MENU_OPTION_ADD_ENTRY="${BRIGHT_BOLD}1)${RESET} ${ELECTRIC_YELLOW}Add new entry${RESET}"
MENU_OPTION_SEARCH_ENTRIES="${BRIGHT_BOLD}2)${RESET} ${ELECTRIC_YELLOW}Search entries${RESET}"
MENU_OPTION_VIEW_ALL_ENTRIES="${BRIGHT_BOLD}3)${RESET} ${ELECTRIC_YELLOW}View all entries${RESET}"
MENU_OPTION_EDIT_ENTRY="${BRIGHT_BOLD}4)${RESET} ${ELECTRIC_YELLOW}Edit existing entry${RESET}"
MENU_OPTION_REMOVE_ENTRY="${BRIGHT_BOLD}5)${RESET} ${ELECTRIC_YELLOW}Remove entry${RESET}"
MENU_OPTION_QUIT="${BRIGHT_BOLD}6)${RESET} ${ELECTRIC_YELLOW}Quit${RESET}"
MENU_OPTION_CHANGE_MASTER_PASSWORD="${BRIGHT_BOLD}7)${RESET} ${ELECTRIC_YELLOW}Change master password${RESET}"
MENU_OPTION_MANAGE_SETTINGS="${BRIGHT_BOLD}8)${RESET} ${ELECTRIC_YELLOW}Manage Settings${RESET}"
MENU_OPTION_LOAD_EXTERNAL_FILE="${BRIGHT_BOLD}9)${RESET} ${ELECTRIC_YELLOW}Load another credentials file${RESET}"
PROMPT_ENTER_CHOICE_MAIN_MENU="Enter your choice [1-9]:"
INFO_GOODBYE="${AQUA}👋 Goodbye! Your data is securely locked.${RESET}"
SUCCESS_MASTER_PASSWORD_UPDATED_MAIN_MENU="${LIME_GREEN}Master password updated successfully.${RESET}"
ERROR_MASTER_PASSWORD_CHANGE_FAILED_REVERT="${NEON_RED}Failed to change master password. Reverting to previous password and data.${RESET}"
SUCCESS_EXTERNAL_FILE_LOADED_MAIN_MENU="${LIME_GREEN}Successfully switched to new credentials file.${RESET}"
ERROR_EXTERNAL_FILE_LOAD_FAILED_REVERT="${ELECTRIC_YELLOW}Failed to load external credentials or operation cancelled. Reverting to previous session.${RESET}"
ERROR_INVALID_MAIN_MENU_OPTION="${NEON_RED}❌ Invalid option. Please enter a number between ${BRIGHT_BOLD}1${RESET}${NEON_RED} and ${BRIGHT_BOLD}9${RESET}${NEON_RED}.${RESET}"
