#!/bin/bash
# lib/_prompts.sh
# Defines all user-facing prompt strings for the Secure Password Manager.
# Modernized for better readability and a clean, colorful interface.

# Source color definitions to use in prompts
source "$(dirname "$0")/lib/_colors.sh"

# --- Master Password Change Prompts (from _change_master.sh) ---
PROMPT_CHANGE_MASTER_TITLE="
${VIOLET}${BRIGHT_BOLD}🔑 CHANGE MASTER PASSWORD${RESET}"
PROMPT_CHANGE_MASTER_HINT="${CYBER_BLUE}First, enter your current master password to authorize the change.${RESET}
"
PROMPT_ENTER_CURRENT_MASTER_PASS="${ELECTRIC_YELLOW}Enter current master password: ${RESET}"
ERROR_NO_PASSWORD_ENTERED="${NEON_RED}🚫 No password entered. Operation cancelled.${RESET}"
ERROR_INCORRECT_CURRENT_MASTER_PASS="${NEON_RED}❌ Incorrect master password. Operation cancelled.${RESET}"
PROMPT_ENTER_NEW_MASTER_PASS="${ELECTRIC_YELLOW}Enter ${BRIGHT_BOLD}NEW${RESET}${ELECTRIC_YELLOW} master password: ${RESET}"
ERROR_NEW_PASSWORD_NOT_SET="${NEON_RED}🚫 New password was not set. Operation cancelled.${RESET}"
WARNING_NEW_PASS_SAME_AS_CURRENT="${ELECTRIC_YELLOW}⚠️ New password is the same as the current one. No changes have been made.${RESET}"
ERROR_ENCRYPT_NEW_PASS_FAILED="${NEON_RED}❌ Critical error: Failed to encrypt data with the new password. Aborting.${RESET}"
ERROR_MOVE_ENCRYPTED_FILE_FAILED="${NEON_RED}❌ Critical error: Failed to move encrypted data file. Check permissions.${RESET}"
SUCCESS_MASTER_PASSWORD_CHANGED="${LIME_GREEN}✅ Master password has been changed successfully!${RESET}"

# --- General Utility Prompts (from _utils.sh) ---
PROMPT_CLEAR_SCREEN_TITLE_LINE1="${VIOLET}╔═══════════════════════════════════════════════════════════╗${RESET}"
PROMPT_CLEAR_SCREEN_TITLE_LINE2="${VIOLET}║               ${AQUA}${BRIGHT_BOLD}✨ Secure Password Manager ✨${VIOLET}               ║${RESET}"
PROMPT_CLEAR_SCREEN_TITLE_LINE3="${VIOLET}╚═══════════════════════════════════════════════════════════╝${RESET}
"
PROMPT_PRESS_ENTER_TO_CONTINUE="
${TEXT_CYAN}Press ${BRIGHT_BOLD}[Enter]${TEXT_CYAN} to continue...${RESET}"
PROMPT_SPINNER_COMPLETE_MESSAGE="${LIME_GREEN}✓ %s complete!${RESET}         
"
PROMPT_MASTER_PASSWORD_INPUT_GENERIC="${ELECTRIC_YELLOW}%s${RESET}" # Placeholder for dynamic prompt
ERROR_MASTER_PASSWORD_EMPTY="${NEON_RED}🚫 Master password cannot be empty. Please try again.${RESET}"
PROMPT_CONFIRM_MASTER_PASSWORD="${ELECTRIC_YELLOW}Confirm your master password: ${RESET}"
ERROR_PASSWORDS_DO_NOT_MATCH="${NEON_RED}🚫 Passwords do not match. Please try again.${RESET}"
PROMPT_OPTIONAL_INPUT_WITH_REMOVE="${ELECTRIC_YELLOW}%s ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN})${RESET} [${TEXT_CYAN}Leave blank to keep, type ${NEON_RED}'x'${TEXT_CYAN} to remove]:${RESET} "
PROMPT_FIELD_WILL_BE_REMOVED="${AQUA}Field will be removed.${RESET}"
PROMPT_MANDATORY_INPUT_CONDITIONAL="${ELECTRIC_YELLOW}%s ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}, cannot be empty):${RESET} "
ERROR_FIELD_CANNOT_BE_EMPTY="${NEON_RED}🚫 This field cannot be empty. Provide a value or type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
WARNING_NO_CLIPBOARD_UTILITY="${ELECTRIC_YELLOW}⚠️ No clipboard utility (like xclip or pbcopy) found. Install one for copy support.${RESET}"

# --- CRUD Operations Prompts (from _crud_operations.sh) ---
# Add Entry
PROMPT_ADD_ENTRY_TITLE="
${VIOLET}${BRIGHT_BOLD}➕ ADD NEW CREDENTIAL${RESET}"
PROMPT_CANCEL_OPERATION_HINT="${CYBER_BLUE}💡 Tip: At any prompt, type ${BRIGHT_BOLD}'c'${CYBER_BLUE} and press Enter to cancel.${RESET}
"
PROMPT_ENTER_WEBSITE_NAME="${AQUA}🌐 Website or Service Name: ${RESET}"
ERROR_WEBSITE_EMPTY="${NEON_RED}🚫 Website/Service name is required. Type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
PROMPT_LOGGED_IN_VIA_DEFAULT="🔗 Login via another service? (e.g. Google) ${TEXT_CYAN}(Default: ${BRIGHT_BOLD}%s${TEXT_CYAN}, blank=none, 'x'=clear):${RESET} "
PROMPT_LOGGED_IN_VIA="🔗 Login via another service? (e.g. Google) ${TEXT_CYAN}(Leave blank if none):${RESET} "
PROMPT_DEFAULT_SERVICE_CLEARED="${AQUA}ℹ️ Default service cleared for this entry.${RESET}"
PROMPT_USING_DEFAULT_SERVICE="${AQUA}ℹ️ Using default service: ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_OPERATION_CANCELLED_RETURN_MENU="${AQUA}🚫 Operation cancelled. Returning to main menu.${RESET}"
PROMPT_LINKED_EMAIL_DEFAULT="📧 Email for ${BRIGHT_BOLD}%s${RESET} ${TEXT_CYAN}(Default: ${BRIGHT_BOLD}%s${TEXT_CYAN}, 'x'=clear, 'c'=cancel):${RESET} "
PROMPT_LINKED_EMAIL="📧 Email for ${BRIGHT_BOLD}%s${RESET} ${TEXT_CYAN}(Required, 'c'=cancel):${RESET} "
PROMPT_DEFAULT_EMAIL_CLEARED="${AQUA}ℹ️ Default email cleared for this entry.${RESET}"
PROMPT_USING_DEFAULT_EMAIL="${AQUA}ℹ️ Using default email: ${BRIGHT_BOLD}%s${RESET}.${RESET}"
ERROR_LINKED_EMAIL_EMPTY="${NEON_RED}🚫 A linked email is required if a service is specified. Type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
PROMPT_ENTER_USERNAME_OPTIONAL="👤 Username ${TEXT_CYAN}(Optional, leave blank if none):${RESET} "
PROMPT_EMAIL_DEFAULT="📧 Email ${TEXT_CYAN}(Default: ${BRIGHT_BOLD}%s${TEXT_CYAN}, 'u'=use username, 'x'=clear):${RESET} "
PROMPT_EMAIL="📧 Email ${TEXT_CYAN}(Required, or type 'u' to use username):${RESET} "
PROMPT_ENTER_USERNAME_MANDATORY="👤 Username ${TEXT_CYAN}(Required):${RESET} "
ERROR_USERNAME_EMPTY="${NEON_RED}🚫 Username is required. Type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
ERROR_EMAIL_EMPTY_OR_USERNAME_OPTION="${NEON_RED}🚫 Email is required. Type ${AQUA}'c'${NEON_RED} to cancel or ${AQUA}'u'${NEON_RED} to use a username instead.${RESET}"
PROMPT_ENTER_USERNAME_OPTIONAL_EMAIL_USED="👤 Username ${TEXT_CYAN}(Optional, leave blank if none):${RESET} "
PROMPT_RECOVERY_EMAIL_OPTIONAL="🚨 Recovery Email ${TEXT_CYAN}(Optional, leave blank if none):${RESET} "
PROMPT_GENERATE_PASSWORD="🔑 Generate a random password for this entry? [${LIME_GREEN}y${RESET}/${NEON_RED}N${RESET}]: "
ERROR_INVALID_YES_NO_INPUT="${NEON_RED}🚫 Invalid input. Please enter ${LIME_GREEN}'y'${NEON_RED} for Yes or ${NEON_RED}'n'${NEON_RED} for No.${RESET}"
PROMPT_GENERATED_PASSWORD="${LIME_GREEN}🔐 Generated password: ${BRIGHT_BOLD}%s${RESET}
"
PROMPT_ENTER_SERVICE_PASSWORD_OPTIONAL="🔑 Service Password ${TEXT_CYAN}(Optional, leave blank if none):${RESET} "
PROMPT_ENTER_WEBSITE_PASSWORD_MANDATORY="🔑 Website Password ${TEXT_CYAN}(Required):${RESET} "
ERROR_WEBSITE_PASSWORD_EMPTY="${NEON_RED}🚫 Website password is required. Type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
PROMPT_REVIEW_NEW_ENTRY="
${CYBER_BLUE}${BRIGHT_BOLD}🔎 REVIEW NEW ENTRY${RESET}"
PROMPT_CONFIRM_SAVE_ENTRY="Do you want to ${LIME_GREEN}${BRIGHT_BOLD}SAVE${RESET} this entry? [${LIME_GREEN}Y${RESET}/${NEON_RED}n${RESET}]: "
PROMPT_ENTRY_NOT_SAVED="${AQUA}ℹ️ Entry not saved. Returning to main menu.${RESET}"
SUCCESS_ENTRY_ADDED_SAVED="${LIME_GREEN}✅ Entry successfully added and saved!${RESET}"

# Edit Entry
PROMPT_EDIT_ENTRY_TITLE="
${VIOLET}${BRIGHT_BOLD}✏️ EDIT CREDENTIAL${RESET}"
PROMPT_NO_ENTRIES_TO_EDIT="${ELECTRIC_YELLOW}⚠️ No entries exist to be edited. Please add an entry first.${RESET}"
PROMPT_CHOOSE_ENTRY_TO_EDIT="${AQUA}Select an entry to edit from the list above.${RESET}"
PROMPT_ENTER_ENTRY_NUMBER_TO_EDIT="Enter the number of the entry to edit [1-%d]: "
ERROR_INVALID_ENTRY_NUMBER="${NEON_RED}🚫 Invalid number. Please enter a number between 1 and %d, or type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
PROMPT_CURRENTLY_SELECTED_ENTRY="
${CYBER_BLUE}${BRIGHT_BOLD}✍️ Now Editing Entry #%d${RESET}"
PROMPT_EDITING_HINT="${CYBER_BLUE}For each field, provide a new value or press Enter to keep the current one.${RESET}"
PROMPT_UPDATE_WEBSITE_NAME="🌐 Website/Service Name ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}):${RESET} "
PROMPT_KEEPING_CURRENT_WEBSITE="${AQUA}✓ Keeping current website: ${BRIGHT_BOLD}%s${RESET}
"
PROMPT_UPDATE_LOGGED_IN_VIA="🔗 Login via"
PROMPT_UPDATE_LINKED_EMAIL="📧 Linked email for %s"
PROMPT_UPDATE_USERNAME_FOR_SERVICE="👤 Username for %s"
WARNING_BOTH_EMAIL_USERNAME_EMPTY_SERVICE_REMOVED="${ELECTRIC_YELLOW}⚠️ 'Logged in via' field cleared because its email and username are now empty.${RESET}"
PROMPT_UPDATE_EMAIL="📧 Email"
PROMPT_UPDATE_USERNAME="👤 Username"
ERROR_EMAIL_OR_USERNAME_REQUIRED="${NEON_RED}🚫 Either Email or Username is required. Please provide a value for at least one.${RESET}"
PROMPT_UPDATE_RECOVERY_EMAIL="🚨 Recovery Email"
PROMPT_GENERATE_NEW_PASSWORD="🔑 Generate a new random password? [${LIME_GREEN}y${RESET}/${NEON_RED}N${RESET}]: "
PROMPT_NEW_PASSWORD_LENGTH="🔢 New password length ${TEXT_CYAN}(default: ${BRIGHT_BOLD}%s${TEXT_CYAN}):${RESET} "
ERROR_INVALID_LENGTH="${NEON_RED}🚫 Invalid length. Please enter a positive number, or type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
PROMPT_INCLUDE_UPPERCASE="⬆️ Include uppercase? ${TEXT_CYAN}(default: ${BRIGHT_BOLD}%s${TEXT_CYAN}):${RESET} "
PROMPT_INCLUDE_NUMBERS="🔢 Include numbers? ${TEXT_CYAN}(default: ${BRIGHT_BOLD}%s${TEXT_CYAN}):${RESET} "
PROMPT_INCLUDE_SYMBOLS="🔣 Include symbols? ${TEXT_CYAN}(default: ${BRIGHT_BOLD}%s${TEXT_CYAN}):${RESET} "
PROMPT_GENERATED_NEW_PASSWORD="${LIME_GREEN}🔐 Generated new password: ${BRIGHT_BOLD}%s${RESET}
"
PROMPT_UPDATE_WEBSITE_PASSWORD="🔑 Website password"
PROMPT_REVIEW_UPDATED_ENTRY="
${CYBER_BLUE}${BRIGHT_BOLD}🔎 REVIEW UPDATED ENTRY${RESET}"
PROMPT_CONFIRM_SAVE_CHANGES="Do you want to ${LIME_GREEN}${BRIGHT_BOLD}SAVE${RESET} these changes? [${LIME_GREEN}Y${RESET}/${NEON_RED}n${RESET}]: "
PROMPT_CHANGES_NOT_SAVED="${AQUA}ℹ️ Changes were not saved. Returning to main menu.${RESET}"
SUCCESS_ENTRY_UPDATED_SAVED="${LIME_GREEN}✅ Entry successfully updated and saved!${RESET}"

# Remove Entry
PROMPT_REMOVE_ENTRY_TITLE="
${VIOLET}${BRIGHT_BOLD}🗑️ REMOVE CREDENTIALS${RESET}"
PROMPT_NO_ENTRIES_TO_REMOVE="${ELECTRIC_YELLOW}⚠️ No entries exist to be removed.${RESET}"
PROMPT_CHOOSE_ENTRY_TO_REMOVE="${AQUA}Select one or more entries to remove from the list above.${RESET}"
PROMPT_ENTER_NUMBERS_TO_REMOVE="Enter entry numbers to remove (e.g., ${BRIGHT_BOLD}1, 3, 5${RESET}): "
ERROR_INVALID_ENTRY_NUMBER_REMOVE="${NEON_RED}🚫 Invalid entry number: '${BRIGHT_BOLD}%s${RESET}${NEON_RED}'. Please use valid numbers, or type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
ERROR_NO_VALID_ENTRIES_SELECTED="${NEON_RED}🚫 No valid entries were selected. Type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
PROMPT_ENTRIES_TO_BE_PERMANENTLY_REMOVED="
${NEON_RED}${BRIGHT_BOLD}🔥 Entries to be Permanently Removed${RESET}"
PROMPT_REMOVING_ENTRY="${TEXT_CYAN}Removing entry %d...${RESET}"
PROMPT_CONFIRM_PERMANENT_REMOVAL="Are you ${BRIGHT_BOLD}SURE${RESET} you want to ${NEON_RED}PERMANENTLY REMOVE${RESET} these entries? [${NEON_RED}y${RESET}/${LIME_GREEN}N${RESET}]: "
ERROR_INVALID_YES_NO_INPUT_REMOVE="${NEON_RED}🚫 Invalid input. Please enter ${NEON_RED}'y'${NEON_RED} for Yes or ${LIME_GREEN}'n'${NEON_RED} for No.${RESET}"
PROMPT_REMOVAL_CANCELLED="${AQUA}ℹ️ Removal cancelled. Returning to main menu.${RESET}"
SUCCESS_ENTRIES_REMOVED="${LIME_GREEN}✅ Selected entries have been removed.${RESET}"
PROMPT_REMOVAL_CANCELLED_GENERIC="${AQUA}ℹ️ Removal cancelled.${RESET}"

# --- Display and Search Prompts (from _display_search.sh) ---
PROMPT_SEARCH_CREDENTIALS_TITLE="
${VIOLET}${BRIGHT_BOLD}🔍 SEARCH CREDENTIALS${RESET}"
PROMPT_SEARCH_FIELDS_HINT="🔎 Select fields to filter by (e.g., 1,3,5), or press Enter to show all.${RESET}
"
PROMPT_SEARCH_ENTER_FIELD_NUMBERS="Enter field numbers to filter by (comma-separated): "
PROMPT_SEARCH_WEBSITE_CONTAINS="${AQUA}🌐 Website contains${RESET}"
PROMPT_SEARCH_EMAIL_CONTAINS="${AQUA}📧 Email contains${RESET}"
PROMPT_SEARCH_USERNAME_CONTAINS="${AQUA}👤 Username contains${RESET}"
PROMPT_SEARCH_LOGGED_IN_VIA_CONTAINS="${AQUA}🔗 'Logged in via' contains${RESET}"
PROMPT_SEARCH_LINKED_EMAIL_CONTAINS="${AQUA}📧 Linked email contains${RESET}"
PROMPT_SEARCH_RECOVERY_EMAIL_CONTAINS="${AQUA}🚨 Recovery email contains${RESET}"
PROMPT_SEARCHING_MESSAGE="${AQUA}🔎 Searching for matching credentials...${RESET}
"
ERROR_NO_MATCHING_ENTRIES="${NEON_RED}❌ No matching entries found with the current filters.${RESET}"
PROMPT_MATCHING_ENTRIES_FOUND="
${LIME_GREEN}${BRIGHT_BOLD}--- Found Matching Entries ---${RESET}"
PROMPT_HOW_TO_COMBINE_FILTERS="${ELECTRIC_YELLOW}How should filters be combined? ${TEXT_CYAN}(Current default: ${BRIGHT_BOLD}%s${TEXT_CYAN})${RESET}"
PROMPT_MATCH_ALL_FILTERS="${AQUA}${BRIGHT_BOLD}1)${RESET} Match ${BRIGHT_BOLD}ALL${RESET} filters (AND)"
PROMPT_MATCH_ANY_FILTER="${AQUA}${BRIGHT_BOLD}2)${RESET} Match ${BRIGHT_BOLD}ANY${RESET} filter (OR)"
PROMPT_ENTER_FILTER_MODE="Enter 1 for AND, 2 for OR ${TEXT_CYAN}[press Enter for default]${RESET}: "
PROMPT_COPY_FIELD_QUESTION="
${ELECTRIC_YELLOW}Copy a field to the clipboard?${RESET}"
PROMPT_ENTER_RESULT_NUMBER_TO_COPY="Enter result number [1-%d] to copy from ${TEXT_CYAN}(or press Enter to skip)${RESET}: "
PROMPT_NO_FIELDS_TO_COPY="${ELECTRIC_YELLOW}⚠️ This entry has no fields that can be copied.${RESET}"
PROMPT_WHICH_FIELD_TO_COPY="${ELECTRIC_YELLOW}Which field do you want to copy?${RESET}"
PROMPT_ENTER_FIELD_NUMBER_TO_COPY="Enter field number [1-%d]: "
SUCCESS_COPIED_TO_CLIPBOARD="${LIME_GREEN}✅ Copied to clipboard!${RESET}"
WARNING_NO_VALUE_FOR_FIELD="${ELECTRIC_YELLOW}⚠️ The selected field has no value.${RESET}"

# View All Entries
PROMPT_VIEW_ALL_CREDENTIALS_TITLE="
${VIOLET}${BRIGHT_BOLD}📂 VIEW ALL CREDENTIALS${RESET}
"
PROMPT_NO_ENTRIES_FOUND_YET="${ELECTRIC_YELLOW}ℹ️ No entries found. Start by adding one from the main menu!${RESET}"
PROMPT_ALL_SAVED_CREDENTIALS="${BRIGHT_BOLD}All saved credentials (%d entries):${RESET}"
PROMPT_COPY_FIELD_FROM_ALL_ENTRIES_QUESTION="
${ELECTRIC_YELLOW}Copy a field to the clipboard?${RESET}"
PROMPT_ENTER_ENTRY_NUMBER_TO_COPY="Enter entry number [1-%d] to copy from ${TEXT_CYAN}(or press Enter to skip)${RESET}: "

# --- Configuration Prompts (from _config.sh) ---
PROMPT_MANAGE_SETTINGS_TITLE="
${VIOLET}${BRIGHT_BOLD}⚙️ MANAGE SETTINGS${RESET}"
PROMPT_MANAGE_SETTINGS_HINT="${AQUA}Configure password generator defaults, data file location, and more.${RESET}
"
PROMPT_CURRENT_SETTINGS="${BRIGHT_BOLD}Current Settings:${RESET}"
PROMPT_SETTING_PASSWORD_LENGTH="  ${AQUA}${BRIGHT_BOLD}1)${RESET} Default Password Length: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_INCLUDE_UPPERCASE="  ${AQUA}${BRIGHT_BOLD}2)${RESET} Include Uppercase: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_INCLUDE_NUMBERS="  ${AQUA}${BRIGHT_BOLD}3)${RESET} Include Numbers: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_INCLUDE_SYMBOLS="  ${AQUA}${BRIGHT_BOLD}4)${RESET} Include Symbols: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_CLIPBOARD_DELAY="  ${AQUA}${BRIGHT_BOLD}5)${RESET} Clipboard Clear Delay (sec): ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_DATA_FILE_LOCATION="  ${AQUA}${BRIGHT_BOLD}6)${RESET} Data File Location: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_SEARCH_MODE="  ${AQUA}${BRIGHT_BOLD}7)${RESET} Default Search Mode: ${BRIGHT_BOLD}%s${RESET} ('and'/'or')"
PROMPT_SETTING_DEFAULT_EMAIL="  ${AQUA}${BRIGHT_BOLD}8)${RESET} Default Email: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_DEFAULT_SERVICE="  ${AQUA}${BRIGHT_BOLD}9)${RESET} Default Service: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_SETTING_BACK_TO_MAIN_MENU="  ${AQUA}${BRIGHT_BOLD}Q)${RESET} Back to Main Menu${RESET}
"
PROMPT_ENTER_SETTING_CHOICE="Enter setting number to change, or 'Q' to quit: "
ERROR_INVALID_OPTION_SETTINGS="${NEON_RED}❌ Invalid option. Please enter a number from 1-9 or 'Q'.${RESET}"
PROMPT_ENTER_NEW_PASSWORD_LENGTH="Enter new default password length ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}, min 1):${RESET} "
ERROR_INVALID_LENGTH_POSITIVE_NUMBER="${NEON_RED}🚫 Invalid length. Please enter a positive number.${RESET}"
SUCCESS_PASSWORD_LENGTH_UPDATED="${LIME_GREEN}✅ Default password length updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_INCLUDE_UPPERCASE_QUESTION="Include uppercase letters? ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}, Y/n):${RESET} "
SUCCESS_INCLUDE_UPPERCASE_UPDATED="${LIME_GREEN}✅ 'Include uppercase' updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_INCLUDE_NUMBERS_QUESTION="Include numbers? ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}, Y/n):${RESET} "
SUCCESS_INCLUDE_NUMBERS_UPDATED="${LIME_GREEN}✅ 'Include numbers' updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_INCLUDE_SYMBOLS_QUESTION="Include symbols? ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}, Y/n):${RESET} "
SUCCESS_INCLUDE_SYMBOLS_UPDATED="${LIME_GREEN}✅ 'Include symbols' updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_ENTER_NEW_CLIPBOARD_DELAY="Enter new clipboard clear delay in seconds ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}, 0=disable):${RESET} "
ERROR_INVALID_DELAY_NON_NEGATIVE="${NEON_RED}🚫 Invalid delay. Please enter a non-negative number.${RESET}"
SUCCESS_CLIPBOARD_DELAY_UPDATED="${LIME_GREEN}✅ Clipboard clear delay updated to ${BRIGHT_BOLD}%s${RESET} seconds.${RESET}"
PROMPT_ENTER_NEW_SAVE_LOCATION="Enter new default data file directory ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}):${RESET} "
ERROR_DIRECTORY_NOT_FOUND="${NEON_RED}🚫 Directory not found. Please enter a valid directory path.${RESET}"
SUCCESS_DATA_FILE_LOCATION_UPDATED="${LIME_GREEN}✅ Default data file location updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
INFO_ENCRYPTED_FILE_LOCATION="${ELECTRIC_YELLOW}ℹ️ Encrypted file will now be saved/loaded from: ${BRIGHT_BOLD}%s${RESET}"
PROMPT_ENTER_NEW_SEARCH_MODE="Enter new default search mode ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}, 'and' or 'or'):${RESET} "
ERROR_INVALID_SEARCH_MODE="${NEON_RED}🚫 Invalid input. Please enter 'and' or 'or'.${RESET}"
SUCCESS_SEARCH_MODE_UPDATED="${LIME_GREEN}✅ Default search mode updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_ENTER_NEW_DEFAULT_EMAIL="Enter new default email ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}, blank=clear, 'c'=cancel):${RESET} "
INFO_DEFAULT_EMAIL_CANCELLED="${AQUA}ℹ️ Default email configuration cancelled.${RESET}"
SUCCESS_DEFAULT_EMAIL_UPDATED="${LIME_GREEN}✅ Default email updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
PROMPT_ENTER_NEW_DEFAULT_SERVICE="Enter new default service ${TEXT_CYAN}(current: ${BRIGHT_BOLD}%s${TEXT_CYAN}, blank=clear, 'c'=cancel):${RESET} "
INFO_DEFAULT_SERVICE_CANCELLED="${AQUA}ℹ️ Default service configuration cancelled.${RESET}"
SUCCESS_DEFAULT_SERVICE_UPDATED="${LIME_GREEN}✅ Default service updated to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
INFO_CONFIG_LOADING="${AQUA}⚙️ Loading configuration from ${BRIGHT_BOLD}%s${AQUA}...${RESET}"
SUCCESS_CONFIG_LOADED="${LIME_GREEN}✅ Configuration loaded.${RESET}
"
WARNING_NO_CONFIG_FILE="${ELECTRIC_YELLOW}⚠️ No configuration file found. Using default settings.${RESET}
"
SUCCESS_CONFIG_SAVED="${LIME_GREEN}✅ Configuration saved to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
SUCCESS_DEFAULT_SAVE_LOCATION_UPDATED="${LIME_GREEN}✅ Default save location updated to: ${BRIGHT_BOLD}%s${RESET}.${RESET}"

# --- Crypto Prompts (from _crypto.sh) ---
INFO_SKIPPING_SAVE_NOT_AUTH="
${CYBER_BLUE}-----------------------------------------------------
  ${BRIGHT_BOLD}🔐 Skipping save: Not authenticated.
${CYBER_BLUE}-----------------------------------------------------${RESET}"
IMPORTANT_SECURITY_REMINDER_HEADER="
${NEON_RED}${BRIGHT_BOLD}--- ❗ IMPORTANT SECURITY REMINDER ---${RESET}"
IMPORTANT_SECURITY_REMINDER_LINE1="${NEON_RED}Your password data was handled in memory this session.${RESET}"
IMPORTANT_SECURITY_REMINDER_LINE2="${NEON_RED}For maximum security, ensure your system is not compromised.${RESET}"
IMPORTANT_SECURITY_REMINDER_LINE3="${NEON_RED}Always close the password manager when not in use.${RESET}"
IMPORTANT_SECURITY_REMINDER_FOOTER="${BRIGHT_BOLD}${NEON_RED}---------------------------------------${RESET}"
SUCCESS_CREDENTIALS_SAVED="${LIME_GREEN}✅ Credentials securely saved to ${BRIGHT_BOLD}%s${RESET}.${RESET}"
ERROR_FAILED_TO_MOVE_ENCRYPTED_DATA="${NEON_RED}❌ Critical: Failed to move encrypted data to final file. Check permissions.${RESET}"

# --- External File Load Prompts (from _data_storage.sh) ---
PROMPT_LOAD_EXTERNAL_TITLE="
${VIOLET}${BRIGHT_BOLD}📂 LOAD EXTERNAL CREDENTIALS FILE${RESET}"
PROMPT_LOAD_EXTERNAL_HINT="${AQUA}💡 Enter the full path to the encrypted .json.enc file you wish to load.${RESET}"
PROMPT_LOAD_EXTERNAL_CANCEL_HINT="${AQUA}Type ${BRIGHT_BOLD}'c'${AQUA} to cancel.${RESET}
"
PROMPT_ENTER_EXTERNAL_FILE_PATH="${ELECTRIC_YELLOW}📁 Path to encrypted file: ${RESET}"
ERROR_FILE_NOT_FOUND="${NEON_RED}❌ File not found at '${BRIGHT_BOLD}%s${NEON_RED}'. Please check the path or type ${AQUA}'c'${NEON_RED} to cancel.${RESET}"
PROMPT_ENTER_EXTERNAL_FILE_MASTER_PASS="🔑 Enter master password for '${BRIGHT_BOLD}%s${ELECTRIC_YELLOW}': ${RESET}"
ERROR_EXTERNAL_MASTER_PASSWORD_NOT_PROVIDED="${NEON_RED}🚫 Master password not provided. Aborting load.${RESET}"
INFO_ATTEMPTING_DECRYPT_EXTERNAL="${AQUA}Decrypting and loading credentials from ${BRIGHT_BOLD}%s${AQUA}...${RESET}"
SUCCESS_EXTERNAL_FILE_LOADED="${LIME_GREEN}✅ Credentials from ${BRIGHT_BOLD}%s${LIME_GREEN} loaded successfully!${RESET}"
PROMPT_MAKE_EXTERNAL_FILE_DEFAULT="Do you want to set this as the ${BRIGHT_BOLD}default${RESET} file for future sessions? [${LIME_GREEN}y${RESET}/${NEON_RED}N${RESET}]: "
INFO_EXTERNAL_FILE_LOADED_TEMPORARILY="${AQUA}ℹ️ File loaded for current session only.${RESET}"
ERROR_INVALID_YES_NO_INPUT_EXTERNAL="${NEON_RED}🚫 Invalid input. Please enter ${LIME_GREEN}'y'${NEON_RED} for Yes or ${NEON_RED}'n'${NEON_RED} for No.${RESET}"
SUCCESS_EXTERNAL_FILE_SET_DEFAULT="${LIME_GREEN}✅ This file is now your default credentials file.${RESET}"
ERROR_FAILED_LOAD_EXTERNAL_CREDENTIALS="${NEON_RED}❌ Failed to load external credentials. Check the password and file integrity.${RESET}"

# --- Main Application (passman.sh) Prompts ---
INFO_DEPENDENCY_CHECKING="${AQUA}Checking system dependencies...${RESET}"
ERROR_JQ_NOT_INSTALLED="${NEON_RED}${BRIGHT_BOLD}Error: 'jq' is not installed.${RESET}
${CYBER_BLUE}Please install 'jq' to use this script (e.g., ${ELECTRIC_YELLOW}sudo apt-get install jq${CYBER_BLUE}).${RESET}"
ERROR_OPENSSL_NOT_INSTALLED="${NEON_RED}${BRIGHT_BOLD}Error: 'openssl' is not installed.${RESET}
${CYBER_BLUE}Please install 'openssl' to use this script (e.g., ${ELECTRIC_YELLOW}sudo apt-get install openssl${CYBER_BLUE}).${RESET}"
WARNING_CLIPBOARD_NOT_AVAILABLE="${ELECTRIC_YELLOW}⚠️ Clipboard utility not found. Install ${BRIGHT_BOLD}xclip${RESET}${ELECTRIC_YELLOW} or ${BRIGHT_BOLD}pbcopy${RESET}${ELECTRIC_YELLOW} for copy support.${RESET}"
SUCCESS_DEPENDENCIES_MET="${LIME_GREEN}✅ All dependencies are met.${RESET}
"
WARNING_NO_ENC_FILE_FOUND="${ELECTRIC_YELLOW}🔑 No encrypted credentials file found at ${BRIGHT_BOLD}%s${RESET}${ELECTRIC_YELLOW}.${RESET}"
INFO_SET_MASTER_PASSWORD_PROMPT="${AQUA}This looks like a first-time setup. Let's create your master password.${RESET}"
WARNING_NO_RECOVERY="${BRIGHT_BOLD}${NEON_RED}🚨 IMPORTANT: There is NO recovery for your master password. Remember it!${RESET}"
PROMPT_SET_NEW_MASTER_PASSWORD="Set your new master password: "
ERROR_MASTER_PASSWORD_NOT_SET_EXIT="${NEON_RED}🚫 Master password not set. Exiting.${RESET}"
SUCCESS_INITIAL_FILE_CREATED="${LIME_GREEN}✅ Initial credentials file created and encrypted!${RESET}"
PROMPT_WELCOME_BACK_TITLE="
${VIOLET}${BRIGHT_BOLD}--- Welcome Back! ---${RESET}"
PROMPT_UNLOCK_CREDENTIALS_HINT="${AQUA}Enter your master password to unlock your credentials.${RESET}
"
PROMPT_ENTER_MASTER_PASSWORD_TO_UNLOCK="🔑 Enter master password: "
ERROR_MASTER_PASSWORD_NOT_PROVIDED_EXIT="${NEON_RED}🚫 Master password not provided. Exiting.${RESET}"
INFO_DECRYPTING_CREDENTIALS="${AQUA}Decrypting credentials from ${BRIGHT_BOLD}%s${AQUA}...${RESET}"
SUCCESS_CREDENTIALS_DECRYPTED="${LIME_GREEN}✅ Credentials decrypted successfully!${RESET}"
ERROR_INCORRECT_MASTER_PASSWORD_OR_CORRUPTED="${NEON_RED}❌ Incorrect master password or corrupted data file. Please try again.${RESET}"
PROMPT_MAIN_MENU_TITLE="
${VIOLET}${BRIGHT_BOLD}--- Main Menu ---${RESET}"
PROMPT_MAIN_MENU_HINT="${AQUA}Select an option to continue.${RESET}
"
MENU_OPTION_ADD_ENTRY="  ${AQUA}${BRIGHT_BOLD}1)${RESET} Add new entry"
MENU_OPTION_SEARCH_ENTRIES="  ${AQUA}${BRIGHT_BOLD}2)${RESET} Search entries"
MENU_OPTION_VIEW_ALL_ENTRIES="  ${AQUA}${BRIGHT_BOLD}3)${RESET} View all entries"
MENU_OPTION_EDIT_ENTRY="  ${AQUA}${BRIGHT_BOLD}4)${RESET} Edit existing entry"
MENU_OPTION_REMOVE_ENTRY="  ${AQUA}${BRIGHT_BOLD}5)${RESET} Remove entry"
MENU_OPTION_QUIT="  ${AQUA}${BRIGHT_BOLD}6)${RESET} Quit"
MENU_OPTION_CHANGE_MASTER_PASSWORD="  ${AQUA}${BRIGHT_BOLD}7)${RESET} Change master password"
MENU_OPTION_MANAGE_SETTINGS="  ${AQUA}${BRIGHT_BOLD}8)${RESET} Manage Settings"
MENU_OPTION_LOAD_EXTERNAL_FILE="  ${AQUA}${BRIGHT_BOLD}9)${RESET} Load another credentials file"
PROMPT_ENTER_CHOICE_MAIN_MENU="Enter your choice [1-9]: "
INFO_GOODBYE="${AQUA}👋 Goodbye! Your data has been securely locked.${RESET}"
SUCCESS_MASTER_PASSWORD_UPDATED_MAIN_MENU="${LIME_GREEN}✅ Master password updated successfully.${RESET}"
ERROR_MASTER_PASSWORD_CHANGE_FAILED_REVERT="${NEON_RED}❌ Master password change failed. Reverting to previous state.${RESET}"
SUCCESS_EXTERNAL_FILE_LOADED_MAIN_MENU="${LIME_GREEN}✅ Successfully switched to new credentials file.${RESET}"
ERROR_EXTERNAL_FILE_LOAD_FAILED_REVERT="${ELECTRIC_YELLOW}⚠️ Failed to load external file or operation was cancelled. Reverting to previous session.${RESET}"
ERROR_INVALID_MAIN_MENU_OPTION="${NEON_RED}❌ Invalid option. Please enter a number between ${BRIGHT_BOLD}1${RESET}${NEON_RED} and ${BRIGHT_BOLD}9${RESET}${NEON_RED}.${RESET}"
